import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '@/libs/metronic/_init_metronic.scss';
import Providers from '@/providers';

const geistSans = localFont({
   src: './fonts/GeistVF.woff',
   variable: '--primary-font-family',
   weight: '100 900',
});
const geistMono = localFont({
   src: './fonts/GeistMonoVF.woff',
   variable: '--secondary-font-family',
   weight: '100 900',
});

export const metadata: Metadata = {
   title: {
      default: 'EPISCAN',
      template: '%s | EPISCAN',
   },
   description: 'Generated by create next app',
};

export default function RootLayoutLayoutLayout({
   children,
}: Readonly<{ children: React.ReactNode }>) {
   return (
      <html lang="pt-BR" data-bs-theme="light">
         <body
            data-kt-sticky="true"
            cz-shortcut-listen="true"
            data-kt-sticky-name="app-header-sticky"
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} app-default`}
            // data-kt-app-header-fixed-mobile="true"
            // data-kt-app-toolbar-enabled="true"
            // data-kt-sticky-app-header-sticky="on"
            // data-kt-app-header-sticky="on"
            // data-kt-scrolltop="on"
         >
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
