import type { Metadata } from 'next';
import localFont from 'next/font/local';

import '@/libs/metronic/_init_metronic.scss';
import Providers from '@/providers';

const geistSans = localFont({
   src: './fonts/GeistVF.woff',
   variable: '--primary-font-family',
   weight: '100 900',
});
const geistMono = localFont({
   src: './fonts/GeistMonoVF.woff',
   variable: '--secondary-font-family',
   weight: '100 900',
});

export const metadata: Metadata = {
   title: 'Bluetrix - Template',
   description: 'Generated by create next app',
};

export default function RootLayoutLayoutLayout({
   children,
}: Readonly<{ children: React.ReactNode }>) {
   return (
      <html lang="pt-BR" data-bs-theme="light">
         <body
            id="kt_app_body"
            data-kt-app-header-fixed-mobile="true"
            data-kt-app-toolbar-enabled="true"
            cz-shortcut-listen="true"
            data-kt-sticky-app-header-sticky="on"
            data-kt-app-header-sticky="on"
            data-kt-scrolltop="on"
            className={`${geistSans.variable} ${geistMono.variable} app-default`}
         >
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
